title: Ancient Future
description: Future Memories â€” Every story is a doorway.
theme: "so-simple-theme"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - assets
header_pages:
  - index.md

include:
  - _includes

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      include: head-custom.html
